### ISSUE TITLE
Typos na lista: use outra

### ISSUE THREAD

**Issue by brunobg** [cristianoascari/paises-no-formato-JSON#1]
Esta lista possui vários typos: "Jornânia",  faltas de acentos como "Italia", etc. Prefira a https://stefangabos.github.io/world_countries/

**Comment by cristianoascari** [comment]
Obrigado por avisar. Já corrigido.

**Comment by brunobg** [comment]
Olha, eram só exemplos que eu dei, pq tem outros erros (Coreia sem acento, só pra dar mais um). Por favor atualize a partir de uma lista correta ou tire o repo do ar para ninguém ter problemas ao usar esta lista como eu tive.

**Comment by cristianoascari** [comment]
É uma lista antiga extraída de um banco offline. Eu precisava da versão em inglês e deixei ambas públicas pois talvez fossem úteis pra alguém. Vou tirar um tempo pra revisar.
